name: SwiftBuildSystemGenerator
fileGroups: [project.yml, .sourcery.yml]
# localPackages:
#   - .

aggregateTargets:
  sourcery:
    buildScripts:
      - name: Sourcery
        script: |
          sourcery

  xcodegen:
    buildScripts:
      - name: Xcodegen
        script: |
          rm -rf *.xcodeproj && xcodegen

  carthage:
    buildScripts:
      - name: Xcodegen
        script: |
          carthage bootstrap --no-use-binaries --platform iOS
