#!/bin/zsh

#####################################################################
# This file contains several functions that can be run as tasks
#
# In order to run them easily, add the following alias to your shell:
# > echo "alias task='./taskfile'" >> ~/.zshrc
#
# After that, you can run the functions as follows:
# > task <function_name>
#####################################################################

# Fail if exit code is not zero, in pipes, and also if variable is not set
# See: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

docs() {
  output="docs"
  rm -rf "$output"
  swift doc generate "Sources/StackGenKit" --module-name StackGen --output "$output"
  rm "$output"/_Footer.md "$output"/_Sidebar.md
  mv "$output"/Home.md "$output"/README.md

  for f in $(find docs -name '*.md'); do
    sed -i '' -E "s/\]\(\/([^\)]*)\)/](\1.md)/g" "$f"
  done
}

cov() {
  # brew install jq
  swift doc coverage "Sources/StackGenKit" --output "dcov.json"
  cat "dcov.json" | jq ".data.totals"
  rm "dcov.json"
}

setup() {
  # mint 0.14.2
  brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/577bc4f3ac6301a3b6b634bd4bac9c5367a667e5/Formula/mint.rb
}

"$@" # Source: https://stackoverflow.com/a/16159057/3203441
