#!/bin/zsh

#####################################################################
# This file contains several functions that can be run as tasks
#
# In order to run them easily, add the following alias to your shell:
# > echo "alias task='./taskfile'" >> ~/.zshrc
#
# After that, you can run the functions as follows:
# > task <function_name>
#####################################################################

# Fail if exit code is not zero, in pipes, and also if variable is not set
# See: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

docs() {
  echo "✨ Intalling sourcedocs"
  curl -Ls https://github.com/eneko/SourceDocs/releases/download/1.1.0/sourcedocs.macos.zip -o /tmp/sourcedocs.macos.zip
  unzip -j -o -d /usr/local/bin /tmp/sourcedocs.macos.zip 
  # brew install graphviz # Optional dependency of sourcedocs: needed for generating the dependency graph

  echo "✨ Running sourcedocs"
  sourcedocs generate --clean --reproducible-docs --spm-module StackGenKit
}

checkLinks() {
  revision=${1:=master}
  cmd="bundle exec awesome_bot \
    --allow-redirect \
    --skip-save-results \
    --set-timeout 5 \
    --base-url https://github.com/acecilia/StackGen/tree/$revision/"
  
  eval "${cmd} README.md"
}

linuxTest() {
  swift test --generate-linuxmain
}

setup() {
  echo "✨ Intalling mint 0.14.2"
  brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/577bc4f3ac6301a3b6b634bd4bac9c5367a667e5/Formula/mint.rb

  echo "✨ Install gem dependencies"
  bundle config set path 'vendor/bundle'
  bundle install
}

"$@" # Source: https://stackoverflow.com/a/16159057/3203441
