name: All

options:
  xcodeGenVersion: {{custom.xcodeGenVersion}}

projectReferences:
{% for module in firstPartyModules|expand %}
  {{module.name}}:
    path: {{module.location.path}}/{{module.name}}.xcodeproj
{% endfor %}

schemes:
  All:
    build:
      targets:
        {% for module in firstPartyModules|expand %}
        {{module.name}}/{{module.name}}Tests: all
        {% endfor %}
    test:
      gatherCoverageData: true
      targets:
      {% for module in firstPartyModules|expand %}
        - name: {{module.name}}/{{module.name}}Tests
          randomExecutionOrder: true
      {% endfor %}
