#if !canImport(ObjectiveC)
import XCTest

extension AAA_Generator {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AAA_Generator = [
        ("test_01_Clean", test_01_Clean),
        ("test_02_SelfGenerate", test_02_SelfGenerate),
        ("test_03_GenerateFixtures", test_03_GenerateFixtures),
    ]
}

extension ContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContextTests = [
        ("testContext", testContext),
    ]
}

extension GenerateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GenerateTests = [
        ("testGenerateWithDifferentTopLevel", testGenerateWithDifferentTopLevel),
        ("StackGen_Swift_BuildSystem_Bazel", StackGen_Swift_BuildSystem_Bazel),
        ("StackGen_Swift_BuildSystem_Cocoapods", StackGen_Swift_BuildSystem_Cocoapods),
        ("StackGen_Swift_BuildSystem_Xcodegen", StackGen_Swift_BuildSystem_Xcodegen),
        ("StackGen_Swift_Starter_CommandLine", StackGen_Swift_Starter_CommandLine),
    ]
}

extension IntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegrationTests = [
        ("StackGen_Swift_BuildSystem_Bazel", StackGen_Swift_BuildSystem_Bazel),
        ("StackGen_Swift_BuildSystem_Cocoapods", StackGen_Swift_BuildSystem_Cocoapods),
        ("StackGen_Swift_BuildSystem_Xcodegen", StackGen_Swift_BuildSystem_Xcodegen),
    ]
}

extension MessageGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MessageGeneratorTests = [
        ("testDecodingErrors", testDecodingErrors),
        ("testStackGenErrors", testStackGenErrors),
        ("testStencilErrors", testStencilErrors),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AAA_Generator.__allTests__AAA_Generator),
        testCase(ContextTests.__allTests__ContextTests),
        testCase(GenerateTests.__allTests__GenerateTests),
        testCase(IntegrationTests.__allTests__IntegrationTests),
        testCase(MessageGeneratorTests.__allTests__MessageGeneratorTests),
    ]
}
#endif
