load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

###########################
# Specify main dependency
###########################

git_repository(
  name = "build_bazel_rules_ios",
  remote = "https://github.com/bazel-ios/rules_ios.git",
  commit = "4f96d7b78af4d8bd5d6eade1bfdbe01616521204", # Latest on master at the time of writing (22-06-2020)
)

# Careful: test runner in version 0.2.11 has some issues: https://github.com/google/xctestrunner/issues/16
http_file(
  name = "xctestrunner",
  executable = 1,
  sha256 = "8b7352f7414de4b54478563c90d55509030baa531696dfe9c4e1bf0617ee5eb0",
  urls = ["https://github.com/google/xctestrunner/releases/download/0.2.12/ios_test_runner.par"]
)

###########################
# Load the rest of the dependencies
###########################

load("@build_bazel_rules_ios//rules:repositories.bzl", "rules_ios_dependencies")
rules_ios_dependencies()

load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")
apple_rules_dependencies()

load("@build_bazel_rules_swift//swift:repositories.bzl", "swift_rules_dependencies")
swift_rules_dependencies()

load("@build_bazel_apple_support//lib:repositories.bzl", "apple_support_dependencies")
apple_support_dependencies()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

###########################
# Cocoapods prebuilt dependencies
###########################

load("@build_bazel_rules_ios//repository_rules:framework_builder.bzl", "build_cocoapods_frameworks")

build_cocoapods_frameworks(
  name = "cocoapods",
  directory = "BazelConfig/ThirdParty"
)
