name: SwiftModule2

options:
  defaultConfig: Release
  bundleIdPrefix: com.acecilia
  transitivelyLinkDependencies: true
  createIntermediateGroups: true
  xcodeGenVersion: 2.15.1

fileGroups: [project.yml]

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: M7D34XPBZX
    IPHONEOS_DEPLOYMENT_TARGET: 13.0

targets:
  SwiftModule2:
    type: framework.static
    platform: iOS
    sources:
    - src/main/swift
    info:
      path: SupportingFiles/SwiftModule2/Info.plist
      properties:
        CFBundleShortVersionString: 0.0.1

  SwiftModule2Tests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        # Needed for getting proper test coverage percentages when using static frameworks
        OTHER_LDFLAGS: -all_load
    sources:
    - src/test/swift
    dependencies:
    - target: SwiftModule2
    info:
      path: SupportingFiles/SwiftModule2Tests/Info.plist

schemes:
  SwiftModule2:
    build:
      targets:
        SwiftModule2: all
    test:
      gatherCoverageData: true
      targets:
        - name: SwiftModule2Tests
          randomExecutionOrder: true
