source 'https://rubygems.org' do
  gem 'lefthook', '{{'{{'}}global.lefthookVersion}}'
  {% if module.name == "StackGen_Swift_BuildSystem_Cocoapods" %}
  gem 'cocoapods', '{{'{{'}}global.cocoapodsVersion}}'
  gem 'cocoapods-binary', '{{'{{'}}global.cocoapodsBinaryVersion}}'
  {% endif %}
end
