install! 'cocoapods',
  :share_schemes_for_development_pods => true

use_frameworks!
workspace 'All'

#################
# Binary setup
#################

# Use binaries instead of source code, to speed up builds
$useBinaries = true

if $useBinaries
    plugin 'cocoapods-binary'
    enable_bitcode_for_prebuilt_frameworks!
end

#################
# Config
#################

{% for module in firstPartyModules|expand where "App" in module.name %}
target '{{module.name}}' do
    platform :ios, '{{global.minimumDeploymentTarget}}'
    project '{{module.location.path}}/{{module.name}}.xcodeproj'
    {% for dependency in module.transitiveDependencies.main|expand %}
    {% if dependency.kind == "firstParty" %}
    pod '{{dependency.name}}', :path => '.', :testspecs => ['Tests']
    {% elif dependency.kind == "thirdParty" %}
    pod '{{dependency.name}}', '{{dependency.version}}', :binary => $useBinaries
    {% endif %}
    {% endfor %}
end
{% endfor %}
