source 'https://rubygems.org' do
  gem 'lefthook', '0.7.1'
  gem 'cocoapods', '1.8.4'
  # gem 'typhoeus', '1.3.1' # Workaround for https://github.com/CocoaPods/CocoaPods/issues/9814
  # gem 'xcodeproj', '1.15.0'
  gem 'cocoapods-binary', '0.4.4'
end
