name: All

options:
  xcodeGenVersion: 2.15.1

projectReferences:
  App:
    path: Libraries/App/App.xcodeproj
  SwiftModule1:
    path: Libraries/SwiftModule1/SwiftModule1.xcodeproj
  SwiftModule2:
    path: Libraries/SwiftModule2/SwiftModule2.xcodeproj
  SwiftModule3:
    path: Libraries/SwiftModule3/SwiftModule3.xcodeproj

schemes:
  All:
    build:
      targets:
        App/AppTests: all
        SwiftModule1/SwiftModule1Tests: all
        SwiftModule2/SwiftModule2Tests: all
        SwiftModule3/SwiftModule3Tests: all
    test:
      gatherCoverageData: true
      targets:
        - name: App/AppTests
          randomExecutionOrder: true
        - name: SwiftModule1/SwiftModule1Tests
          randomExecutionOrder: true
        - name: SwiftModule2/SwiftModule2Tests
          randomExecutionOrder: true
        - name: SwiftModule3/SwiftModule3Tests
          randomExecutionOrder: true
