name: SwiftModule3

options:
  defaultConfig: Release
  bundleIdPrefix: com.acecilia
  transitivelyLinkDependencies: true
  createIntermediateGroups: true
  xcodeGenVersion: 2.15.1

fileGroups: [project.yml]

settings:
  base:
    DEVELOPMENT_TEAM: M7D34XPBZX
    IPHONEOS_DEPLOYMENT_TARGET: 13.0

targets:
  SwiftModule3:
    type: framework.static
    platform: iOS
    sources:
    - src/main/swift
    info:
      path: SupportingFiles/SwiftModule3/Info.plist
      properties:
        CFBundleShortVersionString: 0.0.1

  SwiftModule3Tests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        # Needed for getting proper test coverage percentages when using static frameworks
        OTHER_LDFLAGS: -all_load
    sources:
    - src/test/swift
    dependencies:
    - target: SwiftModule3
    info:
      path: SupportingFiles/SwiftModule3Tests/Info.plist

schemes:
  SwiftModule3:
    build:
      targets:
        SwiftModule3: all
    test:
      gatherCoverageData: true
      targets:
        - name: SwiftModule3Tests
          randomExecutionOrder: true
